<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Rc.Contracts\Rc.Contracts.csproj" />
    <ProjectReference Include="..\Rc.TaskHost\Rc.TaskHost.csproj" />
    <ProjectReference Include="..\Rc.WindowsService\Rc.WindowsService.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Rc.Agent.Tests" />
  </ItemGroup>
</Project>
